<?php
// 阪神電気鉄道 ローマ字辞書
return [
    // 阪神本線（大阪梅田〜元町）
    '大阪梅田' => 'osaka-umeda',
    '福島' => 'fukushima',
    '野田' => 'noda',
    '淀川' => 'yodogawa',
    '姫島' => 'himejima',
    '千船' => 'chibune',
    '杭瀬' => 'kuise',
    '大物' => 'daimotsu',
    '尼崎' => 'amagasaki',
    '出屋敷' => 'deyashiki',
    '尼崎センタープール前' => 'amagasaki-center-pool-mae',
    '武庫川' => 'mukogawa',
    '鳴尾・武庫川女子大前' => 'naruo-mukogawa-joshidaimae',
    '甲子園' => 'koshien',
    '久寿川' => 'kuzugawa',
    '今津' => 'imazu',
    '西宮' => 'nishinomiya',
    '香櫨園' => 'koroen',
    '打出' => 'uchide',
    '芦屋' => 'ashiya',
    '深江' => 'fukae',
    '青木' => 'ogi',
    '魚崎' => 'uozaki',
    '住吉' => 'sumiyoshi',
    '御影' => 'mikage',
    '石屋川' => 'ishiyagawa',
    '新在家' => 'shinzaike',
    '大石' => 'oishi',
    '西灘' => 'nishi-nada',
    '岩屋' => 'iwaya',
    '春日野道' => 'kasuganomichi',
    '神戸三宮' => 'kobe-sannomiya',
    '元町' => 'motomachi',

    // 阪神なんば線（大阪難波〜尼崎）
    '大阪難波' => 'osaka-namba',
    '桜川' => 'sakuragawa',
    'ドーム前' => 'dome-mae',
    '九条' => 'kujo',
    '西九条' => 'nishi-kujo',
    '千鳥橋' => 'chidoribashi',
    '伝法' => 'denpo',
    '福' => 'fuku',
    '出来島' => 'dekijima',

    // 武庫川線（武庫川〜武庫川団地前）
    '東鳴尾' => 'higashi-naruo',
    '洲先' => 'suzaki',
    '武庫川団地前' => 'mukogawa-danchimae',
];
