<?php
// JR東日本 関東路線 ローマ字辞書（山手線・中央線除く）
return [
    // 常磐線（三河島〜取手）
    '三河島' => 'mikawashima',
    '南千住' => 'minami-senju',
    '北千住' => 'kita-senju',
    '綾瀬' => 'ayase',
    '亀有' => 'kameari',
    '金町' => 'kanamachi',
    '松戸' => 'matsudo',
    '北松戸' => 'kita-matsudo',
    '馬橋' => 'mabashi',
    '新松戸' => 'shin-matsudo',
    '北小金' => 'kita-kogane',
    '南柏' => 'minami-kashiwa',
    '柏' => 'kashiwa',
    '北柏' => 'kita-kashiwa',
    '我孫子' => 'abiko',
    '天王台' => 'tennodai',
    '取手' => 'toride',

    // 総武線（錦糸町〜千葉）※中央・総武各停の東側
    '新日本橋' => 'shin-nihombashi',
    '馬喰町' => 'bakurocho',
    '錦糸町' => 'kinshicho',
    '亀戸' => 'kameido',
    '平井' => 'hirai',
    '新小岩' => 'shin-koiwa',
    '小岩' => 'koiwa',
    '市川' => 'ichikawa',
    '本八幡' => 'moto-yawata',
    '下総中山' => 'shimosa-nakayama',
    '西船橋' => 'nishi-funabashi',
    '船橋' => 'funabashi',
    '東船橋' => 'higashi-funabashi',
    '津田沼' => 'tsudanuma',
    '幕張本郷' => 'makuhari-hongo',
    '幕張' => 'makuhari',
    '新検見川' => 'shin-kemigawa',
    '稲毛' => 'inage',
    '西千葉' => 'nishi-chiba',
    '千葉' => 'chiba',

    // 横須賀線（西大井〜久里浜）※品川以北は山手線
    '西大井' => 'nishi-oi',
    '新川崎' => 'shin-kawasaki',
    '横浜' => 'yokohama',
    '保土ヶ谷' => 'hodogaya',
    '東戸塚' => 'higashi-totsuka',
    '戸塚' => 'totsuka',
    '大船' => 'ofuna',
    '北鎌倉' => 'kita-kamakura',
    '鎌倉' => 'kamakura',
    '逗子' => 'zushi',
    '東逗子' => 'higashi-zushi',
    '田浦' => 'taura',
    '横須賀' => 'yokosuka',
    '衣笠' => 'kinugasa',
    '久里浜' => 'kurihama',

    // 京葉線（八丁堀〜蘇我）
    '八丁堀' => 'hatchobori',
    '越中島' => 'etchujima',
    '潮見' => 'shiomi',
    '新木場' => 'shin-kiba',
    '葛西臨海公園' => 'kasai-rinkai-koen',
    '舞浜' => 'maihama',
    '新浦安' => 'shin-urayasu',
    '市川塩浜' => 'ichikawa-shiohama',
    '二俣新町' => 'futamata-shinmachi',
    '南船橋' => 'minami-funabashi',
    '新習志野' => 'shin-narashino',
    '海浜幕張' => 'kaihin-makuhari',
    '検見川浜' => 'kemigawa-hama',
    '稲毛海岸' => 'inage-kaigan',
    '千葉みなと' => 'chiba-minato',
    '蘇我' => 'soga',

    // 埼京線（板橋〜大宮）※大崎〜池袋は山手線
    '板橋' => 'itabashi',
    '十条' => 'jujo',
    '赤羽' => 'akabane',
    '北赤羽' => 'kita-akabane',
    '浮間舟渡' => 'ukima-funado',
    '戸田公園' => 'toda-koen',
    '戸田' => 'toda',
    '北戸田' => 'kita-toda',
    '武蔵浦和' => 'musashi-urawa',
    '中浦和' => 'naka-urawa',
    '南与野' => 'minami-yono',
    '与野本町' => 'yono-honmachi',
    '北与野' => 'kita-yono',
    '大宮' => 'omiya',

    // 高崎線（宮原〜高崎）
    '宮原' => 'miyahara',
    '上尾' => 'ageo',
    '北上尾' => 'kita-ageo',
    '桶川' => 'okegawa',
    '北本' => 'kitamoto',
    '鴻巣' => 'konosu',
    '熊谷' => 'kumagaya',
    '深谷' => 'fukaya',
    '本庄' => 'honjo',
    '高崎' => 'takasaki',

    // 宇都宮線（土呂〜小山）
    '土呂' => 'toro',
    '東大宮' => 'higashi-omiya',
    '蓮田' => 'hasuda',
    '白岡' => 'shiraoka',
    '新白岡' => 'shin-shiraoka',
    '久喜' => 'kuki',
    '古河' => 'koga',
    '小山' => 'oyama',

    // 武蔵野線（府中本町〜西船橋）
    '府中本町' => 'fuchu-honmachi',
    '北府中' => 'kita-fuchu',
    '新秋津' => 'shin-akitsu',
    '東所沢' => 'higashi-tokorozawa',
    '新座' => 'niiza',
    '北朝霞' => 'kita-asaka',
    '西浦和' => 'nishi-urawa',
    '南浦和' => 'minami-urawa',
    '東浦和' => 'higashi-urawa',
    '東川口' => 'higashi-kawaguchi',
    '南越谷' => 'minami-koshigaya',
    '越谷レイクタウン' => 'koshigaya-laketown',
    '吉川' => 'yoshikawa',
    '吉川美南' => 'yoshikawa-minami',
    '新三郷' => 'shin-misato',
    '三郷' => 'misato',
    '南流山' => 'minami-nagareyama',
    '新八柱' => 'shin-yahashira',
    '東松戸' => 'higashi-matsudo',
    '市川大野' => 'ichikawa-ono',
    '船橋法典' => 'funabashi-hoten',

    // 南武線（川崎〜立川）
    '川崎' => 'kawasaki',
    '尻手' => 'shitte',
    '矢向' => 'yako',
    '鹿島田' => 'kashimada',
    '平間' => 'hirama',
    '向河原' => 'mukogawara',
    '武蔵小杉' => 'musashi-kosugi',
    '武蔵中原' => 'musashi-nakahara',
    '武蔵新城' => 'musashi-shinjo',
    '武蔵溝ノ口' => 'musashi-mizonokuchi',
    '津田山' => 'tsudayama',
    '久地' => 'kuji',
    '宿河原' => 'shukugawara',
    '登戸' => 'noborito',
    '中野島' => 'nakanoshima-kanagawa',
    '稲田堤' => 'inadazutsumi',
    '矢野口' => 'yanokuchi',
    '稲城長沼' => 'inagi-naganuma',
    '南多摩' => 'minami-tama',
    '府中本町' => 'fuchu-honmachi',
    '西府' => 'nishifu',
    '谷保' => 'yaho',
    '矢川' => 'yagawa',
    '西国立' => 'nishi-kunitachi',
    '立川' => 'tachikawa',

    // 横浜線（東神奈川〜八王子）
    '東神奈川' => 'higashi-kanagawa',
    '大口' => 'oguchi',
    '菊名' => 'kikuna',
    '新横浜' => 'shin-yokohama',
    '小机' => 'kozukue',
    '鴨居' => 'kamoi',
    '中山' => 'nakayama',
    '十日市場' => 'tokaichiba',
    '長津田' => 'nagatsuta',
    '成瀬' => 'naruse',
    '町田' => 'machida',
    '古淵' => 'kobuchi',
    '淵野辺' => 'fuchinobe',
    '矢部' => 'yabe',
    '相模原' => 'sagamihara',
    '橋本' => 'hashimoto',
    '相原' => 'aihara',
    '八王子みなみ野' => 'hachioji-minamino',
    '片倉' => 'katakura',
    '八王子' => 'hachioji',

    // 川越線（大宮〜川越）
    '日進' => 'nisshin',
    '西大宮' => 'nishi-omiya',
    '指扇' => 'sashiogi',
    '南古谷' => 'minami-furuya',

    // 八高線（八王子〜高麗川）
    '北八王子' => 'kita-hachioji',
    '小宮' => 'komiya',
    '拝島' => 'haijima',
    '東福生' => 'higashi-fussa',
    '箱根ヶ崎' => 'hakonegasaki',
    '金子' => 'kaneko',
    '東飯能' => 'higashi-hanno',
    '高麗川' => 'komagawa',
];
