<?php
// JR西日本 アーバンネットワーク ローマ字辞書
return [
    // 大阪環状線
    '大阪' => 'osaka',
    '福島' => 'fukushima',
    '野田' => 'noda',
    '西九条' => 'nishi-kujo',
    '弁天町' => 'bentencho',
    '大正' => 'taisho',
    '芦原橋' => 'ashiharabashi',
    '今宮' => 'imamiya',
    '新今宮' => 'shin-imamiya',
    '天王寺' => 'tennoji',
    '寺田町' => 'teradacho',
    '桃谷' => 'momodani',
    '鶴橋' => 'tsuruhashi',
    '玉造' => 'tamatsukuri',
    '森ノ宮' => 'morinomiya',
    '大阪城公園' => 'osakajo-koen',
    '京橋' => 'kyobashi',
    '桜ノ宮' => 'sakuranomiya',
    '天満' => 'temma',

    // JR京都線（京都〜大阪）
    '京都' => 'kyoto',
    '西大路' => 'nishioji',
    '桂川' => 'katsuragawa',
    '向日町' => 'mukomachi',
    '長岡京' => 'nagaokakyo',
    '山崎' => 'yamazaki',
    '島本' => 'shimamoto',
    '高槻' => 'takatsuki',
    '摂津富田' => 'settsu-tonda',
    '茨木' => 'ibaraki',
    '千里丘' => 'senrioka',
    '岸辺' => 'kishibe',
    '吹田' => 'suita',
    '東淀川' => 'higashi-yodogawa',
    '新大阪' => 'shin-osaka',

    // JR神戸線（大阪〜姫路）
    '塚本' => 'tsukamoto',
    '尼崎' => 'amagasaki',
    '立花' => 'tachibana',
    '甲子園口' => 'koshienguchi',
    '西宮' => 'nishinomiya',
    'さくら夙川' => 'sakura-shukugawa',
    '芦屋' => 'ashiya',
    '摂津本山' => 'settsu-motoyama',
    '住吉' => 'sumiyoshi',
    '六甲道' => 'rokkomichi',
    '灘' => 'nada',
    '三ノ宮' => 'sannomiya',
    '元町' => 'motomachi',
    '神戸' => 'kobe',
    '兵庫' => 'hyogo',
    '新長田' => 'shin-nagata',
    '須磨' => 'suma',
    '垂水' => 'tarumi',
    '舞子' => 'maiko',
    '明石' => 'akashi',
    '西明石' => 'nishi-akashi',
    '加古川' => 'kakogawa',
    '姫路' => 'himeji',

    // JR宝塚線（大阪〜篠山口）
    '塚口' => 'tsukaguchi',
    '伊丹' => 'itami',
    '川西池田' => 'kawanishi-ikeda',
    '中山寺' => 'nakayamadera',
    '宝塚' => 'takarazuka',
    '三田' => 'sanda',
    '篠山口' => 'sasayamaguchi',

    // JR東西線（京橋〜尼崎）
    '大阪天満宮' => 'osaka-temmangu',
    '北新地' => 'kitashinchi',
    '新福島' => 'shin-fukushima',
    '海老江' => 'ebie',
    '御幣島' => 'mitejima',
    '加島' => 'kashima',

    // JR奈良線（京都〜奈良）
    '東福寺' => 'tofukuji',
    '稲荷' => 'inari',
    '宇治' => 'uji',
    '城陽' => 'joyo',
    '木津' => 'kizu',
    '奈良' => 'nara',

    // 阪和線・関西空港線
    '長居' => 'nagai',
    '堺市' => 'sakaishi',
    '三国ヶ丘' => 'mikunigaoka',
    '鳳' => 'otori',
    '和泉府中' => 'izumi-fuchu',
    '東岸和田' => 'higashi-kishiwada',
    '熊取' => 'kumatori',
    '日根野' => 'hineno',
    'りんくうタウン' => 'rinku-town',
    '関西空港' => 'kansai-airport',

    // 大阪東線
    '放出' => 'hanaten',
    '久宝寺' => 'kyuhoji',
];
