<?php
// 京都・神戸 地下鉄 ローマ字辞書
return [
    // 京都市営地下鉄 烏丸線（国際会館〜竹田）
    '国際会館' => 'kokusaikaikan',
    '松ヶ崎' => 'matsugasaki',
    '北山' => 'kitayama',
    '北大路' => 'kitaoji',
    '鞍馬口' => 'kuramaguchi',
    '今出川' => 'imadegawa',
    '丸太町' => 'marutamachi',
    '烏丸御池' => 'karasuma-oike',
    '四条' => 'shijo',
    '五条' => 'gojo',
    '京都' => 'kyoto',
    '九条' => 'kujo',
    '十条' => 'jujo',
    'くいな橋' => 'kuinabashi',
    '竹田' => 'takeda',

    // 京都市営地下鉄 東西線（六地蔵〜太秦天神川）
    '六地蔵' => 'rokujizo',
    '石田' => 'ishida',
    '醍醐' => 'daigo',
    '小野' => 'ono',
    '椥辻' => 'nagitsuji',
    '東野' => 'higashino',
    '山科' => 'yamashina',
    '御陵' => 'misasagi',
    '蹴上' => 'keage',
    '東山' => 'higashiyama',
    '三条京阪' => 'sanjo-keihan',
    '京都市役所前' => 'kyoto-shiyakushomae',
    '二条城前' => 'nijojo-mae',
    '二条' => 'nijo',
    '西大路御池' => 'nishioji-oike',
    '太秦天神川' => 'uzumasa-tenjingawa',

    // 神戸市営地下鉄 西神・山手線（谷上〜西神中央）
    '谷上' => 'tanigami',
    '新神戸' => 'shin-kobe',
    '三宮' => 'sannomiya',
    '県庁前' => 'kenchomae',
    '大倉山' => 'okurayama',
    '湊川公園' => 'minatogawa-koen',
    '上沢' => 'kamisawa',
    '長田' => 'nagata',
    '新長田' => 'shin-nagata',
    '板宿' => 'itayado',
    '妙法寺' => 'myohoji',
    '名谷' => 'myodani',
    '総合運動公園' => 'sogo-undokoen',
    '学園都市' => 'gakuen-toshi',
    '伊川谷' => 'ikawadani',
    '西神南' => 'seishin-minami',
    '西神中央' => 'seishin-chuo',

    // 神戸市営地下鉄 海岸線（三宮・花時計前〜新長田）
    '三宮・花時計前' => 'sannomiya-hanadokeimae',
    '旧居留地・大丸前' => 'kyukyoryuchi-daimarumae',
    'みなと元町' => 'minato-motomachi',
    'ハーバーランド' => 'harbor-land',
    '中央市場前' => 'chuo-ichibamae',
    '和田岬' => 'wadamisaki',
    '御崎公園' => 'misaki-koen',
    '苅藻' => 'karimo',
    '駒ヶ林' => 'komagabayashi',
];
