<?php
// 小田急線 ローマ字辞書
return [
    // 小田急小田原線（新宿〜小田原）
    '新宿' => 'shinjuku',
    '南新宿' => 'minami-shinjuku',
    '参宮橋' => 'sangubashi',
    '代々木八幡' => 'yoyogi-hachiman',
    '代々木上原' => 'yoyogi-uehara',
    '東北沢' => 'higashi-kitazawa',
    '下北沢' => 'shimokitazawa',
    '世田谷代田' => 'setagaya-daita',
    '梅ヶ丘' => 'umegaoka',
    '豪徳寺' => 'gotokuji',
    '経堂' => 'kyodo',
    '千歳船橋' => 'chitose-funabashi',
    '祖師ヶ谷大蔵' => 'soshigaya-okura',
    '成城学園前' => 'seijo-gakuenmae',
    '喜多見' => 'kitami',
    '狛江' => 'komae',
    '和泉多摩川' => 'izumi-tamagawa',
    '登戸' => 'noborito',
    '向ヶ丘遊園' => 'mukogaoka-yuen',
    '生田' => 'ikuta',
    '読売ランド前' => 'yomiuri-land-mae',
    '百合ヶ丘' => 'yurigaoka',
    '新百合ヶ丘' => 'shin-yurigaoka',
    '柿生' => 'kakio',
    '鶴川' => 'tsurukawa',
    '玉川学園前' => 'tamagawa-gakuenmae',
    '町田' => 'machida',
    '相模大野' => 'sagami-ono',
    '小田急相模原' => 'odakyu-sagamihara',
    '相武台前' => 'sobudaimae',
    '座間' => 'zama',
    '海老名' => 'ebina',
    '厚木' => 'atsugi',
    '本厚木' => 'hon-atsugi',
    '愛甲石田' => 'aiko-ishida',
    '伊勢原' => 'isehara',
    '鶴巻温泉' => 'tsurumaki-onsen',
    '東海大学前' => 'tokai-daigakumae',
    '秦野' => 'hadano',
    '渋沢' => 'shibusawa',
    '新松田' => 'shin-matsuda',
    '開成' => 'kaisei',
    '栢山' => 'kayama',
    '富水' => 'tomizu',
    '螢田' => 'hotaruda',
    '足柄' => 'ashigara',
    '小田原' => 'odawara',

    // 小田急江ノ島線（相模大野〜片瀬江ノ島）
    '東林間' => 'higashi-rinkan',
    '中央林間' => 'chuo-rinkan',
    '南林間' => 'minami-rinkan',
    '鶴間' => 'tsuruma',
    '大和' => 'yamato',
    '桜ヶ丘' => 'sakuragaoka',
    '高座渋谷' => 'koza-shibuya',
    '長後' => 'chogo',
    '湘南台' => 'shonandai',
    '六会日大前' => 'mutsuai-nichidaimae',
    '善行' => 'zengyo',
    '藤沢本町' => 'fujisawa-honmachi',
    '藤沢' => 'fujisawa',
    '本鵠沼' => 'hon-kugenuma',
    '鵠沼海岸' => 'kugenuma-kaigan',
    '片瀬江ノ島' => 'katase-enoshima',

    // 小田急多摩線（新百合ヶ丘〜唐木田）
    '五月台' => 'satsukidai',
    '栗平' => 'kurihira',
    '黒川' => 'kurokawa',
    'はるひ野' => 'haruhino',
    '小田急永山' => 'odakyu-nagayama',
    '小田急多摩センター' => 'odakyu-tama-center',
    '唐木田' => 'karakida',
];
