<?php
return [
    '東京' => 'tokyo',
    '有楽町' => 'yurakucho',
    '新橋' => 'shimbashi',
    '浜松町' => 'hamamatsucho',
    '田町' => 'tamachi',
    '高輪ゲートウェイ' => 'takanawa-gateway',
    '品川' => 'shinagawa',
    '大崎' => 'osaki',
    '五反田' => 'gotanda',
    '目黒' => 'meguro',
    '恵比寿' => 'ebisu',
    '渋谷' => 'shibuya',
    '原宿' => 'harajuku',
    '代々木' => 'yoyogi',
    '新宿' => 'shinjuku',
    '新大久保' => 'shin-okubo',
    '高田馬場' => 'takadanobaba',
    '目白' => 'mejiro',
    '池袋' => 'ikebukuro',
    '大塚' => 'otsuka',
    '巣鴨' => 'sugamo',
    '駒込' => 'komagome',
    '田端' => 'tabata',
    '西日暮里' => 'nishi-nippori',
    '日暮里' => 'nippori',
    '鶯谷' => 'uguisudani',
    '上野' => 'ueno',
    '御徒町' => 'okachimachi',
    '秋葉原' => 'akihabara',
    '神田' => 'kanda',
];
