<?php
// 全駅辞書を統合（重複キーは後から登場したものが優先 = array_merge仕様）
return array_merge(
    require __DIR__ . '/yamanote.php',
    require __DIR__ . '/chuo.php',
    require __DIR__ . '/keio.php',
    require __DIR__ . '/odakyu.php',
    require __DIR__ . '/tokyu.php',
    require __DIR__ . '/tokyo-metro.php',
    require __DIR__ . '/keikyu.php',
    require __DIR__ . '/seibu.php',
    require __DIR__ . '/tobu.php',
    require __DIR__ . '/toei.php',
    require __DIR__ . '/jr-east-kanto.php',
    require __DIR__ . '/jr-west.php',
    require __DIR__ . '/hankyu.php',
    require __DIR__ . '/hanshin.php',
    require __DIR__ . '/keihan.php',
    require __DIR__ . '/kintetsu.php',
    require __DIR__ . '/nankai.php',
    require __DIR__ . '/osaka-metro.php',
    require __DIR__ . '/kyoto-kobe-metro.php',
    require __DIR__ . '/jr-central.php',
    require __DIR__ . '/meitetsu.php',
    require __DIR__ . '/nagoya-metro.php',
    require __DIR__ . '/kyushu.php',
    require __DIR__ . '/hokkaido.php',
    require __DIR__ . '/tohoku.php',
    require __DIR__ . '/chugoku.php',
    require __DIR__ . '/shikoku.php',
);
