<?php
// JR東海 ローマ字辞書
return [
    // 東海道新幹線（主要駅）
    '東京' => 'tokyo',
    '品川' => 'shinagawa',
    '新横浜' => 'shin-yokohama',
    '小田原' => 'odawara',
    '熱海' => 'atami',
    '三島' => 'mishima',
    '新富士' => 'shin-fuji',
    '静岡' => 'shizuoka',
    '掛川' => 'kakegawa',
    '浜松' => 'hamamatsu',
    '豊橋' => 'toyohashi',
    '三河安城' => 'mikawa-anjo',
    '名古屋' => 'nagoya',
    '岐阜羽島' => 'gifu-hashima',
    '米原' => 'maibara',
    '京都' => 'kyoto',
    '新大阪' => 'shin-osaka',

    // 東海道本線（熱海〜米原）
    '函南' => 'kannami',
    '沼津' => 'numazu',
    '富士' => 'fuji',
    '興津' => 'okitsu',
    '草薙' => 'kusanagi',
    '清水' => 'shimizu',
    '焼津' => 'yaizu',
    '藤枝' => 'fujieda',
    '島田' => 'shimada',
    '金谷' => 'kanaya',
    '袋井' => 'fukuroi',
    '磐田' => 'iwata',
    '鷲津' => 'washizu',
    '新所原' => 'shin-johara',
    '二川' => 'futagawa',
    '蒲郡' => 'gamagori',
    '岡崎' => 'okazaki',
    '安城' => 'anjo',
    '刈谷' => 'kariya',
    '大府' => 'obu',
    '共和' => 'kyowa',
    '大高' => 'odaka',
    '笠寺' => 'kasadera',
    '熱田' => 'atsuta',
    '金山' => 'kanayama',
    '尾頭橋' => 'otobashi',
    '枇杷島' => 'biwajima',
    '稲沢' => 'inazawa',
    '尾張一宮' => 'owari-ichinomiya',
    '木曽川' => 'kisogawa',
    '岐阜' => 'gifu',
    '穂積' => 'hozumi',
    '大垣' => 'ogaki',
    '関ヶ原' => 'sekigahara',

    // 中央西線（名古屋〜塩尻）
    '鶴舞' => 'tsurumai',
    '千種' => 'chikusa',
    '大曽根' => 'ozone',
    '新守山' => 'shin-moriyama',
    '勝川' => 'kachigawa',
    '春日井' => 'kasugai',
    '神領' => 'jinryo',
    '高蔵寺' => 'kozoji',
    '多治見' => 'tajimi',
    '土岐市' => 'tokishi',
    '瑞浪' => 'mizunami',
    '恵那' => 'ena',
    '中津川' => 'nakatsugawa',
    '南木曽' => 'nagiso',
    '木曽福島' => 'kiso-fukushima',
    '塩尻' => 'shiojiri',

    // 関西本線（名古屋〜亀山）
    '八田' => 'hatta',
    '蟹江' => 'kanie',
    '弥富' => 'yatomi',
    '桑名' => 'kuwana',
    '富田' => 'tomida',
    '四日市' => 'yokkaichi',
    '亀山' => 'kameyama',

    // 紀勢本線（亀山〜鳥羽）
    '津' => 'tsu',
    '松阪' => 'matsusaka',
    '多気' => 'taki',
    '伊勢市' => 'iseshi',
    '鳥羽' => 'toba',

    // 高山本線（岐阜〜飛騨古川）
    '鵜沼' => 'unuma',
    '美濃太田' => 'mino-ota',
    '下呂' => 'gero',
    '高山' => 'takayama',
    '飛騨古川' => 'hida-furukawa',

    // 身延線
    '富士宮' => 'fujinomiya',
    '身延' => 'minobu',
    '甲府' => 'kofu',

    // 飯田線
    '豊川' => 'toyokawa',
    '新城' => 'shinshiro',
    '飯田' => 'iida',
    '天竜峡' => 'tenryukyo',

    // 武豊線
    '半田' => 'handa',
    '武豊' => 'taketoyo',
];
