<?php
// 京急線 ローマ字辞書
return [
    // 京急本線（泉岳寺〜浦賀）
    '泉岳寺' => 'sengakuji',
    '品川' => 'shinagawa',
    '北品川' => 'kita-shinagawa',
    '新馬場' => 'shimbanba',
    '青物横丁' => 'aomono-yokocho',
    '鮫洲' => 'samezu',
    '立会川' => 'tachiaigawa',
    '大森海岸' => 'omori-kaigan',
    '平和島' => 'heiwajima',
    '大森町' => 'omorimachi',
    '梅屋敷' => 'umeyashiki',
    '京急蒲田' => 'keikyu-kamata',
    '雑色' => 'zoshiki',
    '六郷土手' => 'rokugodote',
    '京急川崎' => 'keikyu-kawasaki',
    '八丁畷' => 'hatchonawate',
    '鶴見市場' => 'tsurumi-ichiba',
    '京急鶴見' => 'keikyu-tsurumi',
    '花月総持寺' => 'kagetsu-sojiji',
    '生麦' => 'namamugi',
    '京急新子安' => 'keikyu-shin-koyasu',
    '子安' => 'koyasu',
    '神奈川新町' => 'kanagawa-shinmachi',
    '京急東神奈川' => 'keikyu-higashi-kanagawa',
    '神奈川' => 'kanagawa',
    '横浜' => 'yokohama',
    '戸部' => 'tobe',
    '日ノ出町' => 'hinodecho',
    '黄金町' => 'koganecho',
    '南太田' => 'minami-ota',
    '井土ヶ谷' => 'idogaya',
    '弘明寺' => 'gumyoji',
    '上大岡' => 'kami-ooka',
    '屏風浦' => 'byobugaura',
    '杉田' => 'sugita',
    '京急富岡' => 'keikyu-tomioka',
    '能見台' => 'nokendai',
    '金沢文庫' => 'kanazawa-bunko',
    '金沢八景' => 'kanazawa-hakkei',
    '追浜' => 'oppama',
    '京急田浦' => 'keikyu-taura',
    '安針塚' => 'anjinzuka',
    '逸見' => 'hemi',
    '汐入' => 'shioiri',
    '横須賀中央' => 'yokosuka-chuo',
    '県立大学' => 'kenritsu-daigaku',
    '堀ノ内' => 'horinouchi',
    '京急大津' => 'keikyu-otsu',
    '馬堀海岸' => 'mabori-kaigan',
    '浦賀' => 'uraga',

    // 京急久里浜線（堀ノ内〜三崎口）
    '新大津' => 'shin-otsu',
    '北久里浜' => 'kita-kurihama',
    '京急久里浜' => 'keikyu-kurihama',
    'YRP野比' => 'yrp-nobi',
    '京急長沢' => 'keikyu-nagasawa',
    '津久井浜' => 'tsukuihama',
    '三浦海岸' => 'miura-kaigan',
    '三崎口' => 'misakiguchi',

    // 京急空港線（京急蒲田〜羽田空港）
    '糀谷' => 'kojiya',
    '大鳥居' => 'otorii',
    '穴守稲荷' => 'anamori-inari',
    '天空橋' => 'tenkubashi',
    '羽田空港第3ターミナル' => 'haneda-airport-terminal3',
    '羽田空港第1・第2ターミナル' => 'haneda-airport-terminal1-2',

    // 京急大師線（京急川崎〜小島新田）
    '港町' => 'minatomachi',
    '鈴木町' => 'suzukicho',
    '川崎大師' => 'kawasaki-daishi',
    '東門前' => 'higashi-monzen',
    '大師橋' => 'daishi-bashi',
    '小島新田' => 'kojima-shinden',

    // 京急逗子線（金沢八景〜逗子・葉山）
    '六浦' => 'mutsuura',
    '神武寺' => 'jimmuji',
    '逗子・葉山' => 'zushi-hayama',
];
