<?php
// 京王線 ローマ字辞書
return [
    // 京王線（新宿〜京王八王子）
    '新宿' => 'shinjuku',
    '笹塚' => 'sasazuka',
    '代田橋' => 'daitabashi',
    '明大前' => 'meidaimae',
    '下高井戸' => 'shimo-takaido',
    '桜上水' => 'sakura-josui',
    '上北沢' => 'kami-kitazawa',
    '八幡山' => 'hachimanyama',
    '芦花公園' => 'roka-koen',
    '千歳烏山' => 'chitose-karasuyama',
    '仙川' => 'sengawa',
    'つつじヶ丘' => 'tsutsujigaoka',
    '柴崎' => 'shibasaki',
    '国領' => 'kokuryo',
    '布田' => 'fuda',
    '調布' => 'chofu',
    '西調布' => 'nishi-chofu',
    '飛田給' => 'tobitakyu',
    '武蔵野台' => 'musashinodai',
    '多磨霊園' => 'tama-reien',
    '東府中' => 'higashi-fuchu',
    '府中' => 'fuchu',
    '分倍河原' => 'bubaigawara',
    '中河原' => 'nakagawara',
    '聖蹟桜ヶ丘' => 'seiseki-sakuragaoka',
    '百草園' => 'mogusaen',
    '高幡不動' => 'takahata-fudo',
    '南平' => 'minamidaira',
    '平山城址公園' => 'hirayama-joshi-koen',
    '長沼' => 'naganuma',
    '北野' => 'kitano',
    '京王八王子' => 'keio-hachioji',

    // 京王高尾線（北野〜高尾山口）
    'めじろ台' => 'mejiro-dai',
    '狭間' => 'hazama',
    '高尾' => 'takao',
    '高尾山口' => 'takaosanguchi',

    // 京王新線（新宿〜笹塚）
    '初台' => 'hatsudai',
    '幡ヶ谷' => 'hatagaya',

    // 京王井の頭線（渋谷〜吉祥寺）
    '渋谷' => 'shibuya',
    '神泉' => 'shinsen',
    '駒場東大前' => 'komaba-todaimae',
    '池ノ上' => 'ikenoue',
    '下北沢' => 'shimokitazawa',
    '新代田' => 'shin-daita',
    '東松原' => 'higashi-matsubara',
    '永福町' => 'eifukucho',
    '西永福' => 'nishi-eifuku',
    '浜田山' => 'hamadayama',
    '高井戸' => 'takaido',
    '富士見ヶ丘' => 'fujimigaoka',
    '久我山' => 'kugayama',
    '三鷹台' => 'mitakadai',
    '井の頭公園' => 'inokashira-koen',
    '吉祥寺' => 'kichijoji',

    // 京王相模原線（調布〜橋本）
    '京王多摩川' => 'keio-tamagawa',
    '京王稲田堤' => 'keio-inadazutsumi',
    '京王よみうりランド' => 'keio-yomiuri-land',
    '稲城' => 'inagi',
    '若葉台' => 'wakabadai',
    '京王永山' => 'keio-nagayama',
    '京王多摩センター' => 'keio-tama-center',
    '京王堀之内' => 'keio-horinouchi',
    '南大沢' => 'minami-osawa',
    '多摩境' => 'tamasakai',
    '橋本' => 'hashimoto',
];
