<?php
// 名古屋市営地下鉄・あおなみ線・リニモ ローマ字辞書
return [
    // 東山線（高畑〜藤が丘）
    '高畑' => 'takabata',
    '八田' => 'hatta',
    '岩塚' => 'iwatsuka',
    '中村公園' => 'nakamura-koen',
    '中村日赤' => 'nakamura-nisseki',
    '本陣' => 'honjin',
    '亀島' => 'kamejima',
    '名古屋' => 'nagoya',
    '伏見' => 'fushimi',
    '栄' => 'sakae',
    '新栄町' => 'shinsakaemachi',
    '千種' => 'chikusa',
    '今池' => 'imaike',
    '池下' => 'ikeshita',
    '覚王山' => 'kakuozan',
    '本山' => 'motoyama',
    '東山公園' => 'higashiyama-koen',
    '星ヶ丘' => 'hoshigaoka',
    '一社' => 'issha',
    '上社' => 'kamiyashiro',
    '本郷' => 'hongo',
    '藤が丘' => 'fujigaoka',

    // 名城線（環状）
    '大曽根' => 'ozone',
    'ナゴヤドーム前矢田' => 'nagoya-dome-mae-yada',
    '砂田橋' => 'sunadabashi',
    '茶屋ヶ坂' => 'chayagasaka',
    '自由ヶ丘' => 'jiyugaoka',
    '名古屋大学' => 'nagoya-daigaku',
    '八事日赤' => 'yagoto-nisseki',
    '八事' => 'yagoto',
    '総合リハビリセンター' => 'sogo-rehabilitation-center',
    '瑞穂運動場東' => 'mizuho-undojo-higashi',
    '新瑞橋' => 'aratamabashi',
    '妙音通' => 'myoondori',
    '堀田' => 'hotta',
    '伝馬町' => 'temmacho',
    '神宮西' => 'jingu-nishi',
    '西高蔵' => 'nishi-takakura',
    '金山' => 'kanayama',
    '東別院' => 'higashi-betsuin',
    '上前津' => 'kamimaezu',
    '矢場町' => 'yabacho',
    '久屋大通' => 'hisaya-odori',
    '市役所' => 'shiyakusho',
    '名城公園' => 'meijo-koen',
    '黒川' => 'kurokawa',
    '志賀本通' => 'shiga-hondori',
    '平安通' => 'heian-dori',

    // 名港線（金山〜名古屋港）
    '日比野' => 'hibino',
    '六番町' => 'rokubancho',
    '東海通' => 'tokai-dori',
    '港区役所' => 'minato-kuyakusho',
    '築地口' => 'tsukijiguchi',
    '名古屋港' => 'nagoyako',

    // 鶴舞線（上小田井〜赤池）
    '上小田井' => 'kami-otai',
    '庄内緑地公園' => 'shonai-ryokuchi-koen',
    '庄内通' => 'shonai-dori',
    '浄心' => 'joshin',
    '浅間町' => 'sengencho',
    '丸の内' => 'marunouchi',
    '大須観音' => 'osu-kannon',
    '鶴舞' => 'tsurumai',
    '荒畑' => 'arahata',
    '御器所' => 'gokiso',
    '川名' => 'kawana',
    'いりなか' => 'irinaka',
    '塩釜口' => 'shiogamaguchi',
    '植田' => 'ueda',
    '原' => 'hara',
    '平針' => 'hirabari',
    '赤池' => 'akaike',

    // 桜通線（中村区役所〜徳重）
    '中村区役所' => 'nakamura-kuyakusho',
    '国際センター' => 'kokusai-center',
    '高岳' => 'takaoka',
    '車道' => 'shamichi',
    '吹上' => 'fukiage',
    '桜山' => 'sakurayama',
    '瑞穂区役所' => 'mizuho-kuyakusho',
    '瑞穂運動場西' => 'mizuho-undojo-nishi',
    '桜本町' => 'sakura-honmachi',
    '鶴里' => 'tsurusato',
    '野並' => 'nonami',
    '鳴子北' => 'naruko-kita',
    '相生山' => 'aioiyama',
    '神沢' => 'kamisawa-nagoya',
    '徳重' => 'tokushige',

    // あおなみ線（名古屋〜金城ふ頭）
    'ささしまライブ' => 'sasashima-live',
    '小本' => 'komoto',
    '荒子' => 'arako',
    '南荒子' => 'minami-arako',
    '中島' => 'nakashima',
    '名古屋競馬場前' => 'nagoya-keibajo-mae',
    '荒子川公園' => 'arakogawa-koen',
    '稲永' => 'inaei',
    '野跡' => 'noseki',
    '金城ふ頭' => 'kinjo-futo',

    // リニモ（藤が丘〜八草）
    'はなみずき通' => 'hanamizuki-dori',
    '杁ヶ池公園' => 'irigaike-koen',
    '長久手古戦場' => 'nagakute-kosenjo',
    '芸大通' => 'geidai-dori',
    '公園西' => 'koen-nishi',
    '愛・地球博記念公園' => 'ai-chikyuhaku-kinen-koen',
    '陶磁資料館南' => 'toji-shiryokan-minami',
    '八草' => 'yakusa',
];
