<?php
// 大阪メトロ・大阪モノレール ローマ字辞書
return [
    // 御堂筋線（江坂〜なかもず）
    '江坂' => 'esaka',
    '東三国' => 'higashi-mikuni',
    '新大阪' => 'shin-osaka',
    '西中島南方' => 'nishi-nakajima-minamikata',
    '中津' => 'nakatsu',
    '梅田' => 'umeda',
    '淀屋橋' => 'yodoyabashi',
    '本町' => 'hommachi',
    '心斎橋' => 'shinsaibashi',
    'なんば' => 'namba',
    '大国町' => 'daikokucho',
    '動物園前' => 'dobutsuen-mae',
    '天王寺' => 'tennoji',
    '昭和町' => 'showacho',
    '西田辺' => 'nishi-tanabe',
    '長居' => 'nagai',
    'あびこ' => 'abiko',
    '北花田' => 'kita-hanada',
    '新金岡' => 'shin-kanaoka',
    'なかもず' => 'nakamozu',

    // 谷町線（大日〜八尾南）
    '大日' => 'dainichi',
    '守口' => 'moriguchi',
    '太子橋今市' => 'taishibashi-imaichi',
    '千林大宮' => 'senbayashi-omiya',
    '関目高殿' => 'sekime-takadono',
    '野江内代' => 'noe-uchindai',
    '都島' => 'miyakojima',
    '天神橋筋六丁目' => 'tenjimbashisuji-rokuchome',
    '中崎町' => 'nakazakicho',
    '東梅田' => 'higashi-umeda',
    '南森町' => 'minami-morimachi',
    '天満橋' => 'temmabashi',
    '谷町四丁目' => 'tanimachi-yonchome',
    '谷町六丁目' => 'tanimachi-rokuchome',
    '谷町九丁目' => 'tanimachi-kyuchome',
    '四天王寺前夕陽ヶ丘' => 'shitennojimae-yuhigaoka',
    '阿倍野' => 'abeno',
    '文の里' => 'fuminosato',
    '田辺' => 'tanabe',
    '駒川中野' => 'komagawa-nakano',
    '平野' => 'hirano',
    '喜連瓜破' => 'kire-uriwari',
    '出戸' => 'deto',
    '長原' => 'nagahara',
    '八尾南' => 'yao-minami',

    // 四つ橋線（西梅田〜住之江公園）
    '西梅田' => 'nishi-umeda',
    '肥後橋' => 'higobashi',
    '四ツ橋' => 'yotsubashi',
    '花園町' => 'hanazonocho',
    '岸里' => 'kishinosato',
    '玉出' => 'tamade',
    '北加賀屋' => 'kita-kagaya',
    '住之江公園' => 'suminoe-koen',

    // 中央線（コスモスクエア〜長田）
    'コスモスクエア' => 'cosmosquare',
    '大阪港' => 'osakako',
    '朝潮橋' => 'asashiobashi',
    '九条' => 'kujo',
    '阿波座' => 'awaza',
    '堺筋本町' => 'sakaisuji-hommachi',
    '緑橋' => 'midoribashi',
    '深江橋' => 'fukaebashi',
    '高井田' => 'takaida',
    '長田' => 'nagata',

    // 千日前線（野田阪神〜南巽）
    '野田阪神' => 'noda-hanshin',
    '玉川' => 'tamagawa-osaka',
    '西長堀' => 'nishi-nagahori',
    '桜川' => 'sakuragawa',
    '日本橋' => 'nippombashi',
    '新深江' => 'shin-fukae',
    '小路' => 'shoji',
    '北巽' => 'kita-tatsumi',
    '南巽' => 'minami-tatsumi',

    // 堺筋線（天神橋筋六丁目〜天下茶屋）
    '扇町' => 'ogimachi',
    '北浜' => 'kitahama',
    '長堀橋' => 'nagahoribashi',
    '恵美須町' => 'ebisucho',
    '天下茶屋' => 'tengachaya',

    // 長堀鶴見緑地線（大正〜門真南）
    '大正' => 'taisho',
    'ドーム前千代崎' => 'dome-mae-chiyozaki',
    '西大橋' => 'nishi-ohashi',
    '松屋町' => 'matsuyamachi',
    '大阪ビジネスパーク' => 'osaka-business-park',
    '京橋' => 'kyobashi',
    '蒲生四丁目' => 'gamo-yonchome',
    '今福鶴見' => 'imafuku-tsurumi',
    '横堤' => 'yokozutsumi',
    '鶴見緑地' => 'tsurumi-ryokuchi',
    '門真南' => 'kadoma-minami',

    // 今里筋線（井高野〜今里）
    '井高野' => 'itakano',
    '瑞光四丁目' => 'zuiko-yonchome',
    'だいどう豊里' => 'daido-toyosato',
    '清水' => 'shimizu',
    '新森古市' => 'shinmori-furuichi',
    '関目成育' => 'sekime-seiiku',
    '鴫野' => 'shigino',

    // 南港ポートタウン線・ニュートラム（コスモスクエア〜住之江公園）
    'トレードセンター前' => 'trade-center-mae',
    '中ふ頭' => 'naka-futo',
    'ポートタウン西' => 'port-town-nishi',
    'ポートタウン東' => 'port-town-higashi',
    'フェリーターミナル' => 'ferry-terminal',
    '南港東' => 'nanko-higashi',
    '南港口' => 'nankoguchi',
    '平林' => 'hirabayashi',

    // 大阪モノレール（大阪空港〜門真市）
    '大阪空港' => 'osaka-kuko',
    '柴原阪大前' => 'shibahara-handaimae',
    '少路' => 'shoji-toyonaka',
    '千里中央' => 'senri-chuo',
    '万博記念公園' => 'bampaku-kinen-koen',
    '宇野辺' => 'unobe',
    '沢良宜' => 'sawaragi',
    '摂津' => 'settsu',
    '南摂津' => 'minami-settsu',
];
