<?php
// 東急線 ローマ字辞書
return [
    // 東横線（渋谷〜横浜）
    '渋谷' => 'shibuya',
    '代官山' => 'daikanyama',
    '中目黒' => 'naka-meguro',
    '祐天寺' => 'yutenji',
    '学芸大学' => 'gakugei-daigaku',
    '都立大学' => 'toritsu-daigaku',
    '自由が丘' => 'jiyugaoka',
    '田園調布' => 'denenchofu',
    '多摩川' => 'tamagawa',
    '新丸子' => 'shin-maruko',
    '武蔵小杉' => 'musashi-kosugi',
    '元住吉' => 'motosumiyoshi',
    '日吉' => 'hiyoshi',
    '綱島' => 'tsunashima',
    '大倉山' => 'okurayama',
    '菊名' => 'kikuna',
    '妙蓮寺' => 'myorenji',
    '白楽' => 'hakuraku',
    '東白楽' => 'higashi-hakuraku',
    '反町' => 'tanmachi',
    '横浜' => 'yokohama',

    // 目黒線（目黒〜日吉）※田園調布〜日吉は東横線と共有
    '目黒' => 'meguro',
    '不動前' => 'fudomae',
    '武蔵小山' => 'musashi-koyama',
    '西小山' => 'nishi-koyama',
    '洗足' => 'senzoku',
    '大岡山' => 'ookayama',
    '奥沢' => 'okusawa',

    // 田園都市線（渋谷〜中央林間）
    '池尻大橋' => 'ikejiri-ohashi',
    '三軒茶屋' => 'sangenjaya',
    '駒沢大学' => 'komazawa-daigaku',
    '桜新町' => 'sakura-shinmachi',
    '用賀' => 'yoga',
    '二子玉川' => 'futako-tamagawa',
    '二子新地' => 'futako-shinchi',
    '高津' => 'takatsu',
    '溝の口' => 'mizonokuchi',
    '梶が谷' => 'kajigaya',
    '宮崎台' => 'miyazakidai',
    '宮前平' => 'miyamaedaira',
    '鷺沼' => 'saginuma',
    'たまプラーザ' => 'tama-plaza',
    'あざみ野' => 'azamino',
    '江田' => 'eda',
    '市が尾' => 'ichigao',
    '藤が丘' => 'fujigaoka',
    '青葉台' => 'aobadai',
    '田奈' => 'tana',
    '長津田' => 'nagatsuta',
    'つくし野' => 'tsukushino',
    'すずかけ台' => 'suzukakedai',
    '南町田グランベリーパーク' => 'minami-machida-grandberry-park',
    'つきみ野' => 'tsukimino',
    '中央林間' => 'chuo-rinkan',

    // 大井町線（大井町〜溝の口）
    '大井町' => 'oimachi',
    '下神明' => 'shimo-shinmei',
    '戸越公園' => 'togoshi-koen',
    '中延' => 'nakanobu',
    '荏原町' => 'ebaramachi',
    '旗の台' => 'hatanodai',
    '北千束' => 'kita-senzoku',
    '緑が丘' => 'midorigaoka',
    '九品仏' => 'kuhombutsu',
    '尾山台' => 'oyamadai',
    '等々力' => 'todoroki',
    '上野毛' => 'kaminoge',

    // 池上線（五反田〜蒲田）
    '五反田' => 'gotanda',
    '大崎広小路' => 'osaki-hirokoji',
    '戸越銀座' => 'togoshi-ginza',
    '荏原中延' => 'ebara-nakanobu',
    '長原' => 'nagahara',
    '洗足池' => 'senzoku-ike',
    '石川台' => 'ishikawadai',
    '雪が谷大塚' => 'yukigaya-otsuka',
    '御嶽山' => 'ontakesan',
    '久が原' => 'kugahara',
    '千鳥町' => 'chidoricho',
    '池上' => 'ikegami',
    '蓮沼' => 'hasunuma',
    '蒲田' => 'kamata',

    // 東急多摩川線（多摩川〜蒲田）
    '沼部' => 'numabe',
    '鵜の木' => 'unoki',
    '下丸子' => 'shimo-maruko',
    '武蔵新田' => 'musashi-nitta',
    '矢口渡' => 'yaguchinowatashi',

    // 世田谷線（三軒茶屋〜下高井戸）
    '西太子堂' => 'nishi-taishido',
    '若林' => 'wakabayashi',
    '松陰神社前' => 'shoin-jinja-mae',
    '世田谷' => 'setagaya',
    '上町' => 'kamimachi',
    '宮の坂' => 'miyanosaka',
    '山下' => 'yamashita',
    '松原' => 'matsubara',
    '下高井戸' => 'shimo-takaido',

    // こどもの国線（長津田〜こどもの国）
    '恩田' => 'onda',
    'こどもの国' => 'kodomo-no-kuni',
];
