<?php
// 東京メトロ ローマ字辞書
return [
    // 銀座線（浅草〜渋谷）
    '浅草' => 'asakusa',
    '田原町' => 'tawaramachi',
    '稲荷町' => 'inaricho',
    '上野' => 'ueno',
    '上野広小路' => 'ueno-hirokoji',
    '末広町' => 'suehirocho',
    '神田' => 'kanda',
    '三越前' => 'mitsukoshimae',
    '日本橋' => 'nihombashi',
    '京橋' => 'kyobashi',
    '銀座' => 'ginza',
    '新橋' => 'shimbashi',
    '虎ノ門' => 'toranomon',
    '溜池山王' => 'tameike-sanno',
    '赤坂見附' => 'akasaka-mitsuke',
    '青山一丁目' => 'aoyama-itchome',
    '外苑前' => 'gaien-mae',
    '表参道' => 'omotesando',
    '渋谷' => 'shibuya',

    // 丸ノ内線（池袋〜荻窪）
    '池袋' => 'ikebukuro',
    '新大塚' => 'shin-otsuka',
    '茗荷谷' => 'myogadani',
    '後楽園' => 'korakuen',
    '本郷三丁目' => 'hongo-sanchome',
    '御茶ノ水' => 'ochanomizu',
    '淡路町' => 'awajicho',
    '大手町' => 'otemachi',
    '東京' => 'tokyo',
    '霞ヶ関' => 'kasumigaseki',
    '国会議事堂前' => 'kokkai-gijidomae',
    '四ツ谷' => 'yotsuya',
    '四谷三丁目' => 'yotsuya-sanchome',
    '新宿御苑前' => 'shinjuku-gyoenmae',
    '新宿三丁目' => 'shinjuku-sanchome',
    '新宿' => 'shinjuku',
    '西新宿' => 'nishi-shinjuku',
    '中野坂上' => 'nakano-sakaue',
    '新中野' => 'shin-nakano',
    '東高円寺' => 'higashi-koenji',
    '新高円寺' => 'shin-koenji',
    '南阿佐ヶ谷' => 'minami-asagaya',
    '荻窪' => 'ogikubo',

    // 丸ノ内線方南町支線
    '中野新橋' => 'nakano-shimbashi',
    '中野富士見町' => 'nakano-fujimicho',
    '方南町' => 'honancho',

    // 日比谷線（北千住〜中目黒）
    '北千住' => 'kita-senju',
    '南千住' => 'minami-senju',
    '三ノ輪' => 'minowa',
    '入谷' => 'iriya',
    '仲御徒町' => 'naka-okachimachi',
    '秋葉原' => 'akihabara',
    '小伝馬町' => 'kodemmacho',
    '人形町' => 'ningyocho',
    '茅場町' => 'kayabacho',
    '八丁堀' => 'hatchobori',
    '築地' => 'tsukiji',
    '東銀座' => 'higashi-ginza',
    '日比谷' => 'hibiya',
    '虎ノ門ヒルズ' => 'toranomon-hills',
    '神谷町' => 'kamiyacho',
    '六本木' => 'roppongi',
    '広尾' => 'hiroo',
    '恵比寿' => 'ebisu',
    '中目黒' => 'naka-meguro',

    // 東西線（中野〜西船橋）
    '中野' => 'nakano',
    '落合' => 'ochiai',
    '高田馬場' => 'takadanobaba',
    '早稲田' => 'waseda',
    '神楽坂' => 'kagurazaka',
    '飯田橋' => 'iidabashi',
    '九段下' => 'kudanshita',
    '竹橋' => 'takebashi',
    '門前仲町' => 'monzen-nakacho',
    '木場' => 'kiba',
    '東陽町' => 'toyocho',
    '南砂町' => 'minami-sunamachi',
    '西葛西' => 'nishi-kasai',
    '葛西' => 'kasai',
    '浦安' => 'urayasu',
    '南行徳' => 'minami-gyotoku',
    '行徳' => 'gyotoku',
    '妙典' => 'myoden',
    '原木中山' => 'baraki-nakayama',
    '西船橋' => 'nishi-funabashi',

    // 千代田線（代々木上原〜北綾瀬）
    '代々木上原' => 'yoyogi-uehara',
    '代々木公園' => 'yoyogi-koen',
    '明治神宮前' => 'meiji-jingumae',
    '乃木坂' => 'nogizaka',
    '赤坂' => 'akasaka',
    '二重橋前' => 'nijubashimae',
    '新御茶ノ水' => 'shin-ochanomizu',
    '湯島' => 'yushima',
    '根津' => 'nezu',
    '千駄木' => 'sendagi',
    '西日暮里' => 'nishi-nippori',
    '町屋' => 'machiya',
    '綾瀬' => 'ayase',
    '北綾瀬' => 'kita-ayase',

    // 有楽町線（和光市〜新木場）
    '和光市' => 'wakoshi',
    '地下鉄成増' => 'chikatetsu-narimasu',
    '地下鉄赤塚' => 'chikatetsu-akatsuka',
    '平和台' => 'heiwadai',
    '氷川台' => 'hikawadai',
    '小竹向原' => 'kotake-mukaihara',
    '千川' => 'senkawa',
    '要町' => 'kanamecho',
    '東池袋' => 'higashi-ikebukuro',
    '護国寺' => 'gokokuji',
    '江戸川橋' => 'edogawabashi',
    '市ヶ谷' => 'ichigaya',
    '麹町' => 'kojimachi',
    '永田町' => 'nagatacho',
    '桜田門' => 'sakuradamon',
    '有楽町' => 'yurakucho',
    '銀座一丁目' => 'ginza-itchome',
    '新富町' => 'shintomicho',
    '月島' => 'tsukishima',
    '豊洲' => 'toyosu',
    '辰巳' => 'tatsumi',
    '新木場' => 'shin-kiba',

    // 半蔵門線（渋谷〜押上）
    '半蔵門' => 'hanzomon',
    '神保町' => 'jimbocho',
    '水天宮前' => 'suitengumae',
    '清澄白河' => 'kiyosumi-shirakawa',
    '住吉' => 'sumiyoshi',
    '錦糸町' => 'kinshicho',
    '押上' => 'oshiage',

    // 南北線（目黒〜赤羽岩淵）
    '白金台' => 'shirokanedai',
    '白金高輪' => 'shirokane-takanawa',
    '麻布十番' => 'azabu-juban',
    '六本木一丁目' => 'roppongi-itchome',
    '東大前' => 'todaimae',
    '本駒込' => 'hon-komagome',
    '駒込' => 'komagome',
    '西ヶ原' => 'nishigahara',
    '王子' => 'oji',
    '王子神谷' => 'oji-kamiya',
    '志茂' => 'shimo',
    '赤羽岩淵' => 'akabane-iwabuchi',

    // 副都心線（和光市〜渋谷）※和光市〜小竹向原は有楽町線と共有
    '雑司が谷' => 'zoshigaya',
    '西早稲田' => 'nishi-waseda',
    '東新宿' => 'higashi-shinjuku',
    '北参道' => 'kita-sando',
];
