<?php

namespace Database\Seeders;

use App\Models\SeoFeature;
use Illuminate\Database\Seeder;

class SeoFeatureSeeder extends Seeder
{
    public function run(): void
    {
        // ローカルにあるが本番にない6件を削除
        SeoFeature::whereIn('slug', [
            'abs-equipped',
            'budget-50-100man',
            'lady-rider',
            'large-under-150man',
            'touring-long',
            'twin-engine',
        ])->delete();

        $features = [
            [
                'slug' => 'commute-125cc',
                'title' => '通勤・通学におすすめの125cc以下バイク',
                'meta_description' => '通勤・通学に最適な125cc以下の原付二種バイクを特集。燃費が良く維持費も安い、毎日使える実用的な1台を見つけましょう。全国の在庫から価格・走行距離を比較できます。',
                'content_header' => '<p>毎日の通勤・通学にバイクを使いたいなら、<strong>125cc以下の原付二種</strong>がおすすめです。普通自動車免許に小型限定を追加するだけで乗れるうえ、燃費は30〜50km/Lと経済的。車体価格も手頃で、任意保険はファミリーバイク特約が使えるため維持費を大幅に抑えられます。</p><p>通勤ラッシュの渋滞をすり抜け、駐輪場にもコンパクトに収まる125ccクラス。PCX、アドレス125、ジョグなど人気モデルの在庫をチェックして、快適な通勤ライフを始めましょう。</p>',
                'guide_content' => '125ccバイク（原付二種）は原付と異なり二段階右折が不要で、法定速度は60km/hまで出せます。年間の維持費は自賠責保険・任意保険（ファミリーバイク特約）・税金を合わせて約3〜5万円程度と非常に経済的。通勤距離が片道10km以内であれば、電車やクルマよりもコストパフォーマンスに優れています。選ぶ際のチェックポイントは、燃費（カタログ値30km/L以上が目安）、シート高（足つきの良さ）、メットインなどの収納力の3つです。',
                'search_conditions' => ['max_displacement' => 125, 'min_displacement' => 50],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain_desc',
                'is_active' => true,
                'sort_order' => 10,
                'icon' => 'zap',
                'color' => 'bg-gradient-to-br from-blue-500 to-cyan-400',
            ],
            [
                'slug' => 'budget-under-20man',
                'title' => '20万円以下の中古バイク',
                'meta_description' => '20万円以下で買える中古バイクを一覧表示。通勤・通学や初めてのバイクに最適な格安車両を価格・車種・地域で比較できます。',
                'content_header' => '20万円以下で手に入る中古バイクを集めました。初めてのバイクや通勤用に、コスパの良い1台を見つけましょう。',
                'guide_content' => '20万円以下のバイクは原付スクーターや125ccクラスが中心です。走行距離や年式をチェックし、整備記録のある車両を選ぶと安心です。任意保険やヘルメットなどの初期費用も考慮して予算を組みましょう。',
                'search_conditions' => ['max_price' => 20],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 13,
                'icon' => 'piggy-bank',
                'color' => 'bg-emerald-600',
            ],
            [
                'slug' => 'budget-under-30man',
                'title' => '30万円以下の中古バイク',
                'meta_description' => '30万円以下の中古バイクを価格順で一覧表示。125cc〜250ccの人気車種が手の届く価格で見つかります。',
                'content_header' => '予算30万円以下で見つかる中古バイクの一覧です。125ccから250ccまで、選択肢が一気に広がる価格帯です。',
                'guide_content' => '30万円あれば125cc〜250ccクラスの人気車種に手が届きます。PCX、レブル250、ニンジャ250など選択肢が豊富。車検不要の250cc以下なら維持費も抑えられます。',
                'search_conditions' => ['max_price' => 30],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 14,
                'icon' => 'wallet',
                'color' => 'bg-emerald-500',
            ],
            [
                'slug' => 'budget-under-50man',
                'title' => '50万円以下の中古バイク',
                'meta_description' => '50万円以下の中古バイクを検索。250cc〜400ccの中型から大型バイクまで幅広い選択肢があります。',
                'content_header' => '50万円以下で購入できる中古バイクです。中型から大型まで、本格的なバイクライフを始めるのに最適な価格帯です。',
                'guide_content' => '50万円以下なら400ccクラスや大型の不人気車も狙えます。SR400やCB400SFなど定番ネイキッドに加え、年式が古めの大型ツアラーも射程圏内。車検費用を含めた年間維持費を計算してから選びましょう。',
                'search_conditions' => ['max_price' => 50],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 15,
                'icon' => 'banknote',
                'color' => 'bg-emerald-700',
            ],
            [
                'slug' => 'beginner-recommend',
                'title' => '初心者におすすめのバイク',
                'meta_description' => 'バイク初心者におすすめの中古車を厳選。扱いやすい250cc以下、50万円以下の車両を中心にご紹介。',
                'content_header' => '初めてバイクを買う方におすすめの車両を集めました。扱いやすい排気量と手頃な価格で、安心してバイクライフをスタートできます。',
                'guide_content' => '初心者には車重が軽く足つきの良い250cc以下がおすすめです。車検不要で維持費も安く、立ちゴケしても修理代が抑えられます。人気のPCX、レブル250、ニンジャ250は中古の流通量が多く、パーツも手に入りやすいのがメリットです。',
                'search_conditions' => ['max_price' => 50, 'max_displacement' => 250],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 16,
                'icon' => 'graduation-cap',
                'color' => 'bg-sky-500',
            ],
            [
                'slug' => 'women-recommend',
                'title' => '女性におすすめのバイク',
                'meta_description' => '女性ライダーにおすすめの中古バイク。足つきが良く軽量な125cc〜250ccモデルを中心にご紹介。',
                'content_header' => '女性ライダーにおすすめの軽量で扱いやすいバイクを集めました。足つき良好・軽量な車種で、安心してライディングを楽しめます。',
                'guide_content' => 'シート高が低く車重200kg以下のモデルが取り回しやすくおすすめです。PCX、ビーノ、レブル250は女性人気が高い定番モデル。まずは教習所で乗った車種に近いものから始めると安心です。',
                'search_conditions' => ['max_price' => 50, 'max_displacement' => 250],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 17,
                'icon' => 'heart',
                'color' => 'bg-pink-500',
            ],
            [
                'slug' => 'touring-recommend',
                'title' => 'ツーリング向けおすすめバイク',
                'meta_description' => 'ツーリングに最適な中古バイクを一覧表示。長距離が快適な250cc以上のモデルを厳選。',
                'content_header' => 'ロングツーリングに最適なバイクを集めました。風防・積載性・燃費に優れた車種で、快適な旅を楽しみましょう。',
                'guide_content' => 'ツーリングには250cc以上で航続距離が長いモデルが最適です。Vストローム250、PCX160、CB400SFなどは燃費と快適性のバランスが良い定番。シートの快適さ、パニアケースの取付可否もチェックポイントです。',
                'search_conditions' => ['min_displacement' => 250],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 18,
                'icon' => 'map',
                'color' => 'bg-amber-600',
            ],
            [
                'slug' => 'large-bike-recommend',
                'title' => '大型バイクおすすめ',
                'meta_description' => '401cc以上の大型バイクを一覧検索。ネイキッド・ツアラー・アドベンチャーなど多彩なジャンルから選べます。',
                'content_header' => '圧倒的なパワーと存在感の大型バイク。401cc以上のおすすめ車両を集めました。',
                'guide_content' => '大型バイクは高速道路での余裕が最大の魅力です。ただし車重300kg超のモデルは取り回しに慣れが必要。初めての大型ならCB650RやSV650など、ミドルクラスから始めるのもおすすめです。',
                'search_conditions' => ['min_displacement' => 401],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 19,
                'icon' => 'gauge',
                'color' => 'bg-indigo-600',
            ],
            [
                'slug' => 'short-riders-250cc',
                'title' => '足つきが良い250cc以下バイク',
                'meta_description' => '足つきの良い250cc以下のバイクを特集。シート高が低めで初心者や小柄なライダーも安心して乗れるモデルを厳選。全国の中古・新車在庫を比較できます。',
                'content_header' => '<p>バイク選びで気になるのが「足つき」。特に初心者や小柄なライダーにとって、<strong>両足が地面にしっかり届くかどうか</strong>は安心感に直結します。250ccクラスなら車検不要で維持費もお手頃。</p><p>レブル250、ニンジャ250、PCXなどシート高が低めの人気モデルから、あなたの体格にぴったりの1台を見つけてください。中古なら足回りのカスタム済み車両も狙い目です。</p>',
                'guide_content' => '足つきに不安がある方は、シート高760mm以下を目安に探すのがおすすめです。ただしシート幅や車体の絞り込み形状によって実際の足つき感は変わるため、数値だけで判断せず実車にまたがることが大切。中古車なら「ローダウン済み」「シートあんこ抜き」のカスタム車両もあり、さらに足つきが良くなっている場合があります。初心者の方は、車両重量が軽い（150kg以下）モデルを選ぶと取り回しも楽になります。',
                'search_conditions' => ['max_displacement' => 250],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 20,
                'icon' => 'user',
                'color' => 'bg-gradient-to-br from-green-500 to-emerald-400',
            ],
            [
                'slug' => '150cc-bike',
                'title' => '150ccバイクの中古車',
                'meta_description' => '150ccバイクの中古車一覧。高速道路も走れるコンパクトなサイズが魅力。PCX160、ジクサー150など。',
                'content_header' => '高速道路も走れる150ccクラスのバイクを集めました。小型二輪免許で乗れるコンパクトで経済的な選択肢です。',
                'guide_content' => '150ccは125ccより少しパワーがあり高速道路にも乗れるのが最大のメリット。PCX160、ジクサー150、CBR150Rなどが人気です。維持費は250ccとほぼ同等ですが車体が軽いので取り回しが楽です。',
                'search_conditions' => ['max_displacement' => 160, 'min_displacement' => 126],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 20,
                'icon' => 'zap',
                'color' => 'bg-cyan-600',
            ],
            [
                'slug' => 'low-mileage',
                'title' => '低走行の中古バイク一覧｜走行距離1万km以下',
                'meta_description' => '低走行（走行距離1万km以下）の中古バイクを掲載中。消耗が少なく状態の良い車両を、価格・年式で比較できます。',
                'content_header' => '走行距離1万km以下の低走行車両を集めました。状態の良いバイクをお探しの方におすすめです。',
                'guide_content' => '走行距離が少ない車両は消耗部品の交換頻度が少なく、エンジンの状態も良好なことが多いです。ただし長期放置車は別途注意が必要。バッテリーやタイヤの製造年もチェックしましょう。',
                'search_conditions' => ['max_mileage' => 10000],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 21,
                'icon' => 'activity',
                'color' => 'bg-violet-600',
            ],
            [
                'slug' => 'recent-model',
                'title' => '高年式（3年以内）の中古バイク',
                'meta_description' => '直近3年以内の高年式中古バイクを一覧表示。新車に近いコンディションの車両を探せます。',
                'content_header' => '2023年以降の高年式モデルを集めました。新車に近い状態の中古バイクをお得に手に入れるチャンスです。',
                'guide_content' => '高年式車は最新の安全装備（ABS、トラクションコントロール等）が搭載されている可能性が高く、メーカー保証が残っている場合もあります。新車との価格差が大きいモデルほどお買い得です。',
                'search_conditions' => ['min_model_year' => 2023],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 22,
                'icon' => 'sparkles',
                'color' => 'bg-rose-500',
            ],
            [
                'slug' => 'commute-cub',
                'title' => '燃費最強！カブ系バイク特集',
                'meta_description' => 'スーパーカブ・クロスカブなどカブ系バイクの中古車一覧。圧倒的な燃費と耐久性で通勤・通学に最適。',
                'content_header' => '燃費最強のカブ系バイクを集めました。スーパーカブ、クロスカブ、CT125など、経済性と信頼性を兼ね備えた名車たちです。',
                'guide_content' => 'カブ系はリッター50km以上の燃費と圧倒的な耐久性が魅力。スーパーカブ110は通勤通学の定番、CT125ハンターカブはアウトドア派に人気です。遠心クラッチ式のギアチェンジは慣れると楽しく、カスタムパーツも豊富。',
                'search_conditions' => ['max_displacement' => 125],
                'keyword' => 'カブ',
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 23,
                'icon' => 'leaf',
                'color' => 'bg-emerald-600',
            ],
            [
                'slug' => 'supersport',
                'title' => 'スーパースポーツ・レプリカ特集',
                'meta_description' => 'CBR、YZF、Ninja等のスーパースポーツ中古車一覧。サーキットから峠まで、圧倒的な走行性能を誇るスポーツバイク。',
                'content_header' => '圧倒的な走行性能のスーパースポーツ・レプリカモデルを集めました。CBR、YZF-R、Ninja ZXシリーズなど、所有欲を満たす1台を。',
                'guide_content' => 'スーパースポーツは最新の電子制御（トラクションコントロール、クイックシフター等）搭載モデルが増えています。初めてのSSなら600cc以下のミドルクラスがおすすめ。前傾姿勢がきついので、用途に合うか試乗で確認しましょう。',
                'search_conditions' => ['min_displacement' => 250],
                'keyword' => 'スポーツ',
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 24,
                'icon' => 'flag',
                'color' => 'bg-red-600',
            ],
            [
                'slug' => 'neo-classic',
                'title' => 'ネオクラシック・レトロバイク特集',
                'meta_description' => 'クラシックデザインに最新技術を融合したネオクラシックバイクの中古車一覧。Z900RS、GB350、XSR等。',
                'content_header' => 'レトロなデザインに現代の技術を融合したネオクラシックバイクを集めました。街に映えるスタイルと実用性を両立。',
                'guide_content' => 'ネオクラシックはZ900RS、GB350、XSR700などが代表格。見た目はレトロでもABSやFI等の現代装備が充実しており、日常使いも快適です。カフェレーサーやスクランブラースタイルのカスタムも楽しめます。',
                'search_conditions' => [],
                'keyword' => 'クラシック',
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 25,
                'icon' => 'coffee',
                'color' => 'bg-amber-800',
            ],
            [
                'slug' => 'vintage-bike',
                'title' => '絶版・旧車バイク特集',
                'meta_description' => '2000年以前の絶版・旧車バイクを一覧表示。名車と呼ばれるビンテージモデルを探せます。',
                'content_header' => '時代を超えて愛される絶版・旧車バイクを集めました。CBX400F、RZ250、Z1など、今なお輝く名車たちです。',
                'guide_content' => '旧車は部品供給とメンテナンスが最重要。購入前にパーツの入手性を確認しましょう。専門ショップでの購入がおすすめです。レストア済み車両は高額ですが安心感があります。キャブ車はFI車と異なるメンテナンスが必要です。',
                'search_conditions' => ['max_model_year' => 2000],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 26,
                'icon' => 'clock',
                'color' => 'bg-gray-800',
            ],
            [
                'slug' => 'bargain-pick',
                'title' => 'AIが選ぶお買い得バイク',
                'meta_description' => '相場より安い掘り出し物バイクをAIが自動選定。お得な中古バイクを見つけましょう。',
                'content_header' => '市場相場と比較してお得な車両をAIが自動選定しました。掘り出し物を見逃さないようチェックしましょう。',
                'guide_content' => 'お買い得スコアは同じ車種・年式・走行距離の相場と比較して算出しています。スコアが高いほど市場平均より割安です。ただし安さには理由がある場合も。車両状態・修復歴・付属品を必ず確認しましょう。',
                'search_conditions' => [],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 27,
                'icon' => 'trending-down',
                'color' => 'bg-teal-600',
            ],
            [
                'slug' => 'commute-scooter',
                'title' => '通勤・通学に最適なスクーター特集',
                'meta_description' => '通勤通学におすすめのスクーター中古車一覧。PCX、アドレス、ジョグなど人気モデルを価格比較。',
                'content_header' => '毎日の通勤・通学に最適なスクーターを集めました。メットイン収納・燃費・取り回しの良さが魅力です。',
                'guide_content' => '通勤用スクーターはメットイン容量と燃費がポイント。PCXはバランスが良い定番、アドレスV125は小回りが利き駐輪場にも困りません。雨の日も足元が濡れにくいのがスクーターの大きなメリットです。',
                'search_conditions' => ['max_displacement' => 125],
                'keyword' => 'スクーター',
                'prefecture' => null,
                'sort' => 'bargain',
                'is_active' => true,
                'sort_order' => 28,
                'icon' => 'zap',
                'color' => 'bg-blue-500',
            ],
            [
                'slug' => 'large-under-100man',
                'title' => '100万円以下で買える大型バイク',
                'meta_description' => '支払総額100万円以下で手に入る401cc以上の大型バイクを特集。憧れのリッターバイクも中古ならお手頃価格。全国の在庫から価格比較できます。',
                'content_header' => '<p>「大型バイクに乗りたいけど、予算が心配…」そんなあなたに朗報です。中古市場なら<strong>支払総額100万円以下</strong>で手に入る大型バイクがたくさんあります。</p><p>CB1300SF、ZRX1200、V-Strom650など、人気の大型モデルが予算内で見つかるかも。高速道路でのゆとりある走り、長距離ツーリングの快適さは大型ならでは。価格と状態を比較して、コスパ最強の大型バイクを見つけましょう。</p>',
                'guide_content' => '大型バイク（401cc以上）は大型自動二輪免許が必要で、車検は2年ごとに必須です。車検費用は業者に依頼して5〜8万円程度。中古で100万円以下の大型は5〜15年落ちが中心ですが、日本車は耐久性が高く、整備されていれば十分現役で走れます。購入時はエンジンの異音・オイル漏れ・フロントフォークのオイルにじみをチェック。走行距離は3万km以下が理想ですが、整備履歴がしっかりしていれば5万km超えでも問題ありません。',
                'search_conditions' => ['max_price' => 100, 'min_displacement' => 401],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 30,
                'icon' => 'coins',
                'color' => 'bg-gradient-to-br from-amber-500 to-yellow-400',
            ],
            [
                'slug' => 'budget-under-10man',
                'title' => '10万円以下の格安バイク',
                'meta_description' => '支払総額10万円以下で買える格安バイクを特集。とにかく安くバイクに乗りたい方必見。全国の激安バイク在庫を一覧で比較。',
                'content_header' => '<p>とにかく安くバイクに乗りたい方必見！<strong>支払総額10万円以下</strong>の格安バイクを一挙掲載しています。</p><p>「初めてのバイクは安い車体で練習したい」「セカンドバイクとして近所の足が欲しい」という方にぴったり。走行距離や年式は多めですが、まだまだ現役で走れる掘り出し物が見つかるかもしれません。気になる車両があれば、早めにショップへ問い合わせましょう。</p>',
                'guide_content' => '10万円以下のバイクは走行距離が多め・年式が古いものが中心です。購入前に必ず確認すべきポイントは、タイヤの溝の残量、チェーンとスプロケットの摩耗、ブレーキパッドの残量、バッテリーの状態です。これらの消耗品を交換すると追加で2〜5万円かかることがあるため、総額で考えましょう。整備履歴（点検記録簿）が残っている車両は安心です。また、人気車種は部品供給が豊富なため、修理の心配が少なくおすすめです。',
                'search_conditions' => ['max_price' => 10],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 40,
                'icon' => 'piggy-bank',
                'color' => 'bg-gradient-to-br from-rose-500 to-red-400',
            ],
            [
                'slug' => 'etc-equipped',
                'title' => 'ETC付きバイク特集',
                'meta_description' => 'ETC車載器付きのバイクを特集。高速道路の料金所をノンストップで通過できるETC搭載車を全国から検索。ツーリングに便利な1台を見つけましょう。',
                'content_header' => '<p>高速道路でのツーリングに欠かせない<strong>ETC車載器</strong>。料金所をノンストップで通過でき、二輪車定率割引などのお得な制度も利用可能です。</p><p>最初からETCが装備されたバイクなら、面倒な取り付け工賃もゼロ。納車後すぐにツーリングに出発できます。ロングツーリング派のあなたに最適な、ETC付きバイクをチェックしてみてください。</p>',
                'guide_content' => 'バイク用ETC車載器は後付けすると本体代+セットアップ+取付工賃で約3〜4万円かかります。最初からETC付きの中古車を選べばそのコストをまるごと節約できます。二輪車のETC利用率はまだ低いため、ETC付き車両は市場で希少価値があります。なおETC2.0対応機は高速道路の一時退出・再進入実験にも対応しているため、ツーリング先での寄り道にも便利です。',
                'search_conditions' => ['tag' => 'ETC'],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 50,
                'icon' => 'credit-card',
                'color' => 'bg-gradient-to-br from-indigo-500 to-blue-400',
            ],
            [
                'slug' => 'new-scooter',
                'title' => 'スクーター特集',
                'meta_description' => '通勤・通学・買い物に便利なスクーターを特集。50cc〜250ccのスクーターを全国の在庫から比較。メットイン収納付きで実用的な1台を見つけましょう。',
                'content_header' => '<p>ATで操作がかんたん、メットインスペースに荷物が入る実用性の高さが魅力の<strong>スクーター</strong>。通勤・通学はもちろん、買い物やちょっとしたお出かけにも大活躍します。</p><p>PCX、NMAX、アドレスなど人気スクーターの在庫をチェック。50ccから250ccまで幅広いラインナップから、あなたのライフスタイルに合った1台を見つけましょう。</p>',
                'guide_content' => 'スクーターはAT（オートマチック）なのでクラッチ操作が不要で、初心者でもすぐに乗りこなせます。50ccは原付免許で乗れますが二段階右折と30km/h制限あり。125ccなら小型限定免許で制限なし、ファミリーバイク特約も使えて維持費最安。250ccは高速道路も走れてロングツーリングにも対応可能。選ぶ際はメットイン容量（フルフェイスが入るか）、USB充電ポートの有無、燃費性能をチェックしましょう。',
                'search_conditions' => ['max_displacement' => 250, 'min_displacement' => 50],
                'keyword' => 'スクーター',
                'prefecture' => null,
                'sort' => 'price_asc',
                'is_active' => true,
                'sort_order' => 60,
                'icon' => 'sparkles',
                'color' => 'bg-gradient-to-br from-purple-500 to-pink-400',
            ],
            [
                'slug' => 'one-owner',
                'title' => 'ワンオーナーの中古バイク一覧｜大切に乗られた1台',
                'meta_description' => 'ワンオーナー（前オーナーが1人だけ）の中古バイクを掲載中。整備履歴が追いやすく状態の良い車両を、価格・走行距離で比較できます。',
                'content_header' => '<p>中古バイク選びで「前のオーナーが大切に乗っていたか」は重要なポイント。<strong>ワンオーナー車</strong>は新車から1人のオーナーだけが乗ってきた車両で、メンテナンス履歴が追いやすく、状態が良い傾向にあります。</p><p>複数人の手を渡っていないぶん、消耗品の交換時期も把握しやすいのが魅力。少し予算を上げてでも、程度の良い1台を手に入れたい方におすすめです。</p>',
                'guide_content' => 'ワンオーナー車は新車購入から1人のオーナーだけが乗り続けた車両で、整備記録が追いやすく状態の良いものが多い傾向にあります。ただし「ワンオーナー」でも走行距離が多い場合や、ガレージ保管と屋外保管では状態が大きく異なります。点検記録簿の有無、オイル交換の頻度、純正部品の残存状況を確認しましょう。同じ車種のマルチオーナー車と比べると5〜15%ほど割高なことが多いですが、後のトラブルリスクを考えると十分価値があります。',
                'search_conditions' => ['tag' => 'ワンオーナー'],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 70,
                'icon' => 'crown',
                'color' => 'bg-gradient-to-br from-yellow-500 to-orange-400',
            ],
            [
                'slug' => '250cc-no-inspection',
                'title' => '車検不要！維持費がお得な250ccバイク',
                'meta_description' => '車検不要で維持費を抑えられる126cc〜250ccクラスのバイクを特集。軽二輪は車検なしで高速道路も走れるコスパ最強クラス。',
                'content_header' => '<p>250ccクラス（126cc〜250cc）の最大の魅力は<strong>車検が不要</strong>なこと。2年ごとの車検費用（数万円〜）がかからないため、大幅に維持費を節約できます。</p><p>それでいて高速道路は問題なく走れるので、ツーリングの自由度は十分。ニンジャ250、CBR250RR、YZF-R25など、250ccスポーツモデルは走りの楽しさも一級品。通勤からツーリングまでオールマイティに活躍する250ccバイクを探してみましょう。</p>',
                'guide_content' => '126〜250ccクラス（軽二輪）は車検不要のため、維持費は年間約5〜8万円（自賠責・任意保険・税金・消耗品）に抑えられます。400ccクラスと比べて年間2〜3万円のコスト差があります。車検がない分、自分で定期的なメンテナンスを行うことが重要です。エンジンオイルは3,000〜5,000kmごと、チェーン清掃は月1回が目安。購入時はフレームの錆、フロントフォークのオイル漏れ、リアサスペンションのへたりを要チェックです。',
                'search_conditions' => ['max_displacement' => 250, 'min_displacement' => 126],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'bargain_desc',
                'is_active' => true,
                'sort_order' => 80,
                'icon' => 'shield-check',
                'color' => 'bg-gradient-to-br from-teal-500 to-green-400',
            ],
            [
                'slug' => 'delivery-business-bike',
                'title' => '雨の日も快適！デリバリー・配達におすすめのビジネスバイク',
                'meta_description' => 'ウーバーイーツなどの配達やビジネス用途に最適な屋根付きバイク（ジャイロキャノピーなど）や、積載力抜群のタフなビジネスバイクを厳選しました。',
                'content_header' => '<p>配達業務を効率化し、雨の日も快適に走れる「働くバイク」を集めました。屋根付きでワイパー装備のジャイロキャノピーや、巨大なリアボックスを積載できるベンリィ、ギアなど、プロ仕様のタフなモデルが揃っています。</p>',
                'guide_content' => 'デリバリー・配達用バイクを選ぶポイントは「積載力」「燃費」「耐久性」の3つ。ジャイロキャノピーは屋根付きで雨天でも快適ですが三輪のため独特の操作感があります。スーパーカブは圧倒的な燃費（リッター60km以上）と耐久性でビジネスユースの定番。ベンリィは低床フラットステップで乗り降りしやすく長時間の配達にも向いています。1日50km以上走る方は燃費を最重視、雨天稼働が多い方は屋根付きモデルを検討しましょう。',
                'search_conditions' => ['bike_model_ids' => [3765, 1674, 3586, 415, 417, 418, 3437, 3438, 419, 420, 421, 3587, 416, 450, 451, 452, 453, 3476, 456, 454, 455, 459, 3444, 3445, 460, 461, 464, 462, 463, 465, 466, 467, 468, 469, 470, 471, 472, 458, 473, 474, 475, 476, 545, 3588, 3589, 3590, 3591, 3462, 546, 547, 3420, 557, 1041, 1042, 3706, 1122, 3310, 3311, 1123, 1044, 1043]],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 90,
                'icon' => 'package',
                'color' => 'bg-gradient-to-br from-orange-500 to-red-400',
            ],
            [
                'slug' => 'full-normal-used',
                'title' => 'フルノーマルの中古バイク一覧｜無改造・純正状態',
                'meta_description' => 'カスタムされていない、メーカー出荷時そのままの状態を保った「フルノーマル」のバイク特集です。前オーナーのクセがなく、信頼性を重視する方に最適です。',
                'content_header' => '<p>中古車選びで「安心」を求めるならフルノーマル車がおすすめ！改造によるバランスの崩れや、予期せぬトラブルのリスクが低く、これから自分好みにカスタムしたい方や、長く安心して乗れる車両だけをピックアップしました。</p>',
                'guide_content' => 'フルノーマル車はメーカーの設計通りの状態が保たれているため、走行性能のバランスが崩れておらず安心して乗れます。カスタム車はマフラー交換でパワーバンドが変わっていたり、サスペンション変更で乗り心地が変わっていることがあります。また車検時にノーマルに戻す手間もかかりません。フルノーマルで状態の良い車両は将来の売却時にもリセールバリューが高い傾向にあります。',
                'search_conditions' => ['tag' => 'ノーマル車'],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 100,
                'icon' => 'shield',
                'color' => 'bg-gradient-to-br from-gray-500 to-gray-400',
            ],
            [
                'slug' => '250cc-4cylinder',
                'title' => '超高回転の咆哮！250cc・4気筒エンジン搭載モデル',
                'meta_description' => 'Ninja ZX-25Rやホーネット、バリオスなど、今や希少となった250ccの並列4気筒（マルチ）エンジンを搭載した熱いバイクの在庫一覧です。',
                'content_header' => '<p>1万回転以上まで回した時の「クォォォン！」というF1マシンのような甲高い排気音。現行のZX-25Rはもちろん、ホーネットやバリオス、ZXR250など、往年の名車たちを含めた「250cc・4気筒」のロマンあふれる車両を集めました。</p>',
                'guide_content' => '250cc4気筒は1990年代に各メーカーが競って開発した黄金時代のバイクが多く、現在は中古でしか手に入らない希少なモデルがほとんどです。現行で唯一新車購入できるのがカワサキ ZX-25R。旧車のホーネット250やバリオスは部品供給に不安があるため、程度の良い個体を見極めることが重要です。エンジンの吹け上がり（スムーズに高回転まで回るか）、キャブレター車は同調の状態、走行距離2万km以下が理想的な購入条件です。',
                'search_conditions' => ['bike_model_ids' => [47, 111, 3503, 3504, 3042, 3043, 3044, 3612, 3613, 810, 4565, 3619, 3620, 3734, 3520]],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 110,
                'icon' => 'gauge',
                'color' => 'bg-gradient-to-br from-red-600 to-rose-500',
            ],
            [
                'slug' => 'camp-adventure',
                'title' => '荷物を積んで大自然へ！キャンプ向けアドベンチャー',
                'meta_description' => 'VストロームやVersys、アフリカツインなど、未舗装路も走れて荷物もたっぷり積める「アドベンチャー」タイプのバイク特集。キャンプツーリングに最適です。',
                'content_header' => '<p>圧倒的な積載力と、長距離を走っても疲れない快適なポジション。そしてフラット林道などの未舗装路も走破できる走破性。いま最も熱い「アドベンチャー」モデルで、テントとシュラフを積んで週末のキャンプツーリングへ出かけませんか？</p>',
                'guide_content' => 'アドベンチャーバイクはアップライトなポジション、長いサスペンションストローク、大容量タンクが特徴で、オンロードからフラット林道まで幅広く走れます。キャンプ道具を積むならパニアケース（サイドケース）の装着が必須。純正オプションが充実しているVストロームやアフリカツインが人気です。250ccクラスのCRF250やセローなら車検不要で維持費も安く、初めてのキャンプツーリングにもおすすめ。シート高が高めなので試乗して足つきを確認しましょう。',
                'search_conditions' => ['bike_model_ids' => [3567, 3568, 3323, 3324, 3575, 4613, 3326, 3327, 4832, 3505, 172, 167, 168, 3331, 169, 173, 3334, 3335, 3336, 649, 650, 651, 652, 654, 653, 655, 656, 657, 634, 641, 635, 3605, 3606, 3022, 636, 637, 3023, 638, 639, 640, 658, 3024, 3066, 715, 716, 714, 713, 3069, 3611, 3070, 720, 719, 3072, 3073, 3074, 3214, 3215, 3217, 3218, 3220, 3221, 3222, 3225, 3226, 3227, 3228, 3717, 4712, 3546, 3557, 364, 4612, 3830, 3831, 1375, 1374, 3234, 1384, 386, 3810, 1460, 1461, 1462, 1463, 1474, 1464, 1465, 508, 509]],
                'keyword' => null,
                'prefecture' => null,
                'sort' => 'latest',
                'is_active' => true,
                'sort_order' => 120,
                'icon' => 'mountain',
                'color' => 'bg-gradient-to-br from-emerald-600 to-green-500',
            ],
        ];

        foreach ($features as $feature) {
            $slug = $feature['slug'];
            unset($feature['slug']);

            // search_conditions は配列のまま渡す（モデルの $casts で自動JSON変換）
            SeoFeature::updateOrCreate(
                ['slug' => $slug],
                $feature,
            );
        }
    }
}
